/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovV29yay9BbGJlcnRvIHdvcmsvUmVsaWFibGUgUGx1bWJpbmcvc291cmNlIGNvZGUvcmVsaWFibGUtcGx1bWJpbmctY2xpZW50L3NyYy9hcHAvYXBwLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0U6L1dvcmsvQWxiZXJ0byB3b3JrL1JlbGlhYmxlIFBsdW1iaW5nL3NvdXJjZSBjb2RlL3JlbGlhYmxlLXBsdW1iaW5nLWNsaWVudC9zcmMvYXBwL2FwcC5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
