/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from './app.component.ngfactory';
import * as i4 from '@angular/common';
import * as i5 from '@angular/platform-browser';
import * as i6 from '@angular/router';
import * as i7 from './app-routing.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i4.NgLocalization,
              i4.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.IterableDiffers,
              i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(4608,i5.DomSanitizer,i5.ɵe,[i4.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,
              (null as any),[i5.DomSanitizer]),i0.ɵmpd(4608,i5.HAMMER_GESTURE_CONFIG,
              i5.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,i5.EVENT_MANAGER_PLUGINS,
              (p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i5.ɵDomEventsPlugin(p0_0),new i5.ɵKeyEventsPlugin(p1_0),
                    new i5.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i4.DOCUMENT,i4.DOCUMENT,i4.DOCUMENT,i5.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i5.EventManager,i5.EventManager,[i5.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i5.ɵDomSharedStylesHost,i5.ɵDomSharedStylesHost,[i4.DOCUMENT]),
          i0.ɵmpd(4608,i5.ɵDomRendererFactory2,i5.ɵDomRendererFactory2,[i5.EventManager,
              i5.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i5.ɵDomRendererFactory2]),i0.ɵmpd(6144,i5.ɵSharedStylesHost,(null as any),
              [i5.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i5.Meta,i5.Meta,[i4.DOCUMENT]),i0.ɵmpd(4608,
              i5.Title,i5.Title,[i4.DOCUMENT]),i0.ɵmpd(5120,i6.ActivatedRoute,i6.ɵf,
              [i6.Router]),i0.ɵmpd(4608,i6.NoPreloading,i6.NoPreloading,([] as any[])),
          i0.ɵmpd(6144,i6.PreloadingStrategy,(null as any),[i6.NoPreloading]),i0.ɵmpd(135680,
              i6.RouterPreloader,i6.RouterPreloader,[i6.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i6.PreloadingStrategy]),i0.ɵmpd(4608,i6.PreloadAllModules,
              i6.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i6.ROUTER_INITIALIZER,
              i6.ɵi,[i6.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i6.ROUTER_INITIALIZER]),i0.ɵmpd(512,i4.CommonModule,i4.CommonModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i5.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,
              () => {
                return [i6.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i6.ɵg,i6.ɵg,[i0.Injector]),i0.ɵmpd(256,
              i0.APP_ID,'ang4-seo-pre',([] as any[])),i0.ɵmpd(2048,i5.ɵTRANSITION_ID,
              (null as any),[i0.APP_ID]),i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,
              p0_1:any,p1_0:any,p2_0:any,p2_1:any,p2_2:any) => {
            return [i5.ɵc(p0_0,p0_1),i6.ɵh(p1_0),i5.ɵf(p2_0,p2_1,p2_2)];
          },[[2,i5.NgProbeToken],[2,i0.NgProbeToken],i6.ɵg,i5.ɵTRANSITION_ID,i4.DOCUMENT,
              i0.Injector]),i0.ɵmpd(512,i0.ApplicationInitStatus,i0.ApplicationInitStatus,
              [[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,i0.ɵe,[i0.NgZone,i0.ɵConsole,
              i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,i0.ApplicationInitStatus]),
          i0.ɵmpd(2048,i0.ApplicationRef,(null as any),[i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,
              i0.ApplicationModule,[i0.ApplicationRef]),i0.ɵmpd(512,i5.BrowserModule,
              i5.BrowserModule,[[3,i5.BrowserModule]]),i0.ɵmpd(1024,i6.ɵa,i6.ɵd,[[3,
              i6.Router]]),i0.ɵmpd(512,i6.UrlSerializer,i6.DefaultUrlSerializer,([] as any[])),
          i0.ɵmpd(512,i6.ChildrenOutletContexts,i6.ChildrenOutletContexts,([] as any[])),
          i0.ɵmpd(256,i6.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i4.LocationStrategy,
              i6.ɵc,[i4.PlatformLocation,[2,i4.APP_BASE_HREF],i6.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i4.Location,i4.Location,[i4.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,
              i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i6.ROUTES,
              () => {
                return [([] as any[])];
              },([] as any[])),i0.ɵmpd(1024,i6.Router,i6.ɵe,[i0.ApplicationRef,i6.UrlSerializer,
              i6.ChildrenOutletContexts,i4.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i6.ROUTES,i6.ROUTER_CONFIGURATION,[2,i6.UrlHandlingStrategy],
              [2,i6.RouteReuseStrategy]]),i0.ɵmpd(512,i6.RouterModule,i6.RouterModule,
              [[2,i6.ɵa],[2,i6.Router]]),i0.ɵmpd(512,i7.AppRoutingModule,i7.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovV29yay9BbGJlcnRvIHdvcmsvUmVsaWFibGUgUGx1bWJpbmcvc291cmNlIGNvZGUvcmVsaWFibGUtcGx1bWJpbmctY2xpZW50L3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9FOi9Xb3JrL0FsYmVydG8gd29yay9SZWxpYWJsZSBQbHVtYmluZy9zb3VyY2UgY29kZS9yZWxpYWJsZS1wbHVtYmluZy1jbGllbnQvc3JjL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
