version: '3'
services:
  mongo:
    image: mongo
    labels:
      - "base_image=mongo"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /db/db:/data/db
      - /db/backups:/backups
      
  api:
    build: .
    restart: always
    ports:
      - "80:3000"
    volumes:
      - /apidata/files:/usr/src/dist/files
    depends_on:
      - mongo