version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /db/db:/data/db
  api:
    image: ahmedgomaa/api:1.0.0
    restart: always
    ports:
      - "80:3000"
    volumes:
      - /apidata/apifiles:/dist/files
    depends_on:
      - mongo